id = input('please insert USERID = ')
user1_for_userId_validation = {#501
    "userId":'1',
    "password":"admin",
    "new_password":"admin",
    "first_name":"admin",
    "last_name":"admin",
    "email":"admin@gmail.com",
    "phone":"923112183869",
    "address1":"s-1/579",
    "address2":"s-1/579",
    "country":"pakistan",
    "city":"karachi",
    "state":"Sindh",
    "zip":"75080",
    "language_preference":"english",
    "favourite_category":"FISH",

}
user2_for_successfull_submission = {
    "userId":id,
    "password":"admin",
    "new_password":"admin",
    "first_name":"admin",
    "last_name":"admin",
    "email":"admin@gmail.com",
    "phone":"923112183869",
    "address1":"s-1/579",
    "address2":"s-1/579",
    "country":"pakistan",
    "city":"karachi",
    "state":"Sindh",
    "zip":"75080",
    "language_preference":"english",
    "favourite_category":"FISH",
    
}
user3_for_password_and_newPassword = {#no error
    "userId":id,
    "password":"admin",
    "new_password":"adminS",
    "first_name":"admin",
    "last_name":"admin",
    "email":"admin@gmail.com",
    "phone":"923112183869",
    "address1":"s-1/579",
    "address2":"s-1/579",
    "country":"pakistan",
    "city":"karachi",
    "state":"Sindh",
    "zip":"75080",
    "language_preference":"english",
    "favourite_category":"FISH",
    
}
user4_for_wrong_email_format = {#no error
    "userId":id,
    "password":"admin",
    "new_password":"admin",
    "first_name":"admin",
    "last_name":"admin",
    "email":"admingmail.com",
    "phone":"923112183869",
    "address1":"s-1/579",
    "address2":"s-1/579",
    "country":"pakistan",
    "city":"karachi",
    "state":"Sindh",
    "zip":"75080",
    "language_preference":"english",
    "favourite_category":"FISH",
    
}
user4_for_wrong_phone_number = {#no error
    "userId":id,
    "password":"admin",
    "new_password":"admin",
    "first_name":"admin",
    "last_name":"admin",
    "email":"admin@gmail.com",
    "phone":"9231",
    "address1":"s-1/579",
    "address2":"s-1/579",
    "country":"pakistan",
    "city":"karachi",
    "state":"Sindh",
    "zip":"75080",
    "language_preference":"english",
    "favourite_category":"FISH",
    
}
